name: Auto-label Issues

on:
  issues:
    types: [opened, reopened]

jobs:
  label_by_device:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Extract Issue Type and Device Selection
        id: parse_issue
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          LABELS_ON_ISSUE="${{ github.event.issue.labels.*.name }}"

          ISSUE_TYPE=""
          DEVICE_SELECTIONS=""
          DEVICES_HEADING=""

          if [[ "$LABELS_ON_ISSUE" == *"bug"* ]]; then
            ISSUE_TYPE="bug_report"
            DEVICES_HEADING="### Device(s)"
          elif [[ "$LABELS_ON_ISSUE" == *"Suggestion"* ]]; then
            ISSUE_TYPE="feature_request"
            DEVICES_HEADING="### Device"
          fi

          echo "Detected Issue Type: $ISSUE_TYPE"
          echo "Looking for heading: '$DEVICES_HEADING'"

          if [ -n "$DEVICES_HEADING" ]; then
            DEVICE_SELECTIONS=$(echo "$ISSUE_BODY" | awk -v RS="" -v heading="$DEVICES_HEADING" '
              $0 ~ heading {
                getline;
                sub(/^[[:space:]]*/, "", $0);
                sub(/[[:space:]]*$/, "", $0);
                print;
                exit;
              }'
            )
          fi

          echo "Extracted Device Selections: '$DEVICE_SELECTIONS'"

          echo "issue_type=$ISSUE_TYPE" >> $GITHUB_OUTPUT
          echo "device_selections=$DEVICE_SELECTIONS" >> $GITHUB_OUTPUT

      - name: Determine Labels to Add
        id: determine_labels
        run: |
          ISSUE_TYPE="${{ steps.parse_issue.outputs.issue_type }}"
          DEVICE_SELECTIONS="${{ steps.parse_issue.outputs.device_selections }}"
          LABELS_TO_ADD=()

          if [ "$ISSUE_TYPE" == "bug_report" ]; then
            if [[ "$DEVICE_SELECTIONS" == *"New 3DS"* || "$DEVICE_SELECTIONS" == *"Old 3DS"* ]]; then
              LABELS_TO_ADD+=("3DS")
            fi
            if [[ "$DEVICE_SELECTIONS" == *"Wii U"* ]]; then
              LABELS_TO_ADD+=("Wii U")
            fi
          elif [ "$ISSUE_TYPE" == "feature_request" ]; then
            if [ "$DEVICE_SELECTIONS" == "3DS" ]; then
              LABELS_TO_ADD+=("3DS")
            elif [ "$DEVICE_SELECTIONS" == "Wii U" ]; then
              LABELS_TO_ADD+=("Wii U")
            fi
          fi

          if [ ${#LABELS_TO_ADD[@]} -gt 0 ]; then
            echo "labels=${LABELS_TO_ADD[*]}" >> $GITHUB_OUTPUT
          else
            echo "labels=" >> $GITHUB_OUTPUT
          fi

      - name: Add Determined Labels to Issue
        if: steps.determine_labels.outputs.labels != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToAdd = '${{ steps.determine_labels.outputs.labels }}'.split(',').map(label => label.trim());
            console.log('Adding labels:', labelsToAdd);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labelsToAdd
            });
